### ISSUE TITLE
Add additional icons

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight-icons#15]
Add icons for uni's in geoblacklight fixture data:
- [x] University of Illinois
- [x] University of Maryland
- [x] Penn State University
- [x] University of Minnesota

Maybe also a generic icons for uni's not in project?

**Comment by krdyke** [comment]
Hey Jack, I'm working on adding icons for the CIC project (which includes all of those listed above and 5 others). I'm missing Michigan, but the rest are viewable at [our fork of geobl-icons](https://github.com/CIC-Geospatial-Data-Discovery-Project/geoblacklight-icons/tree/cicgddp). I can make a PR when it's a complete set. I've tried to make them all 250px squares, although I've had to a battle a few of the SVGs to a stalemate, where I leave them alone and they look okay on the preview page (Maryland for example).

**Comment by mejackreed** [comment]
Let me know if you need any help. I did do some manual simplification of several of the icons. Manual simplification included: 
 - removing multiple layers
 - making everything a single color (Black)

**Comment by krdyke** [comment]
Thanks. I made a first pass with #17. Let me know what you think.
